spring:
  application:
    name: Tao Muzvidziwa Assessment
  datasource:
    url: jdbc:h2:mem:bankbalancedispencingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /discovery-atm/

logging:
  level:
    root: INFO
    za.co.discovery.tao.muzvidziwa: DEBUG

application-config:
  overdraft-limit: 10000