-- ACCOUNT_TYPE
INSERT INTO ACCOUNT_TYPE VALUES ('CHQ', 'Cheque Account', 1);
INSERT INTO ACCOUNT_TYPE VALUES ('CFCA', 'Customer Foreign Currency Account', 0);

-- CLIENT_TYPE
INSERT INTO CLIENT_TYPE VALUES ('I', 'Individual');

-- CLIENT_SUB_TYPE
INSERT INTO CLIENT_SUB_TYPE VALUES ('MAL', 'I', 'Male');

-- CURRENCY
INSERT INTO CURRENCY VALUES ('USD', 2, 'United States dollar');
INSERT INTO CURRENCY VALUES ('ZAR', 2, 'South African rand');

-- CURRENCY_CONVERSION_RATE
INSERT INTO CURRENCY_CONVERSION_RATE VALUES ('USD', '*', '11.6167');
INSERT INTO CURRENCY_CONVERSION_RATE VALUES ('ZAR', '/', '1');

-- DENOMINATION_TYPE
INSERT INTO DENOMINATION_TYPE VALUES ('N', 'Note');
INSERT INTO DENOMINATION_TYPE VALUES ('C', 'Coin');

-- DENOMINATION
INSERT INTO DENOMINATION VALUES (1, 10, 'N');
INSERT INTO DENOMINATION VALUES (10, 5, 'C');

-- CLIENT
INSERT INTO CLIENT VALUES (1, 'Mr', 'John', 'Doe', DATE '1980-01-01', 'MAL');

-- CLIENT_ACCOUNT
INSERT INTO CLIENT_ACCOUNT VALUES ('1001', 1, 'CHQ', 'ZAR', 1000.00);
INSERT INTO CLIENT_ACCOUNT VALUES ('1002', 1, 'CFCA', 'USD', 500.00);

-- CREDIT_CARD_LIMIT (if needed for repository)
-- (No minimal data needed unless you have repository methods for this table)

-- ATM
INSERT INTO ATM VALUES (1, 'ATM1', 'Test Location');

-- ATM_ALLOCATION
INSERT INTO ATM_ALLOCATION VALUES (DEFAULT, 1, 1, 10);
INSERT INTO ATM_ALLOCATION VALUES (DEFAULT, 1, 10, 5);