-- ACCOUNT_TYPE
INSERT INTO ACCOUNT_TYPE VALUES ('CHQ', 'Cheque Account', 1);
INSERT INTO ACCOUNT_TYPE VALUES ('CFCA', 'Customer Foreign Currency Account', 0);
INSERT INTO ACCOUNT_TYPE VALUES ('CCRD', 'Credit Card', 1);
INSERT INTO ACCOUNT_TYPE VALUES ('SVGS', 'Savings Account', 1);
INSERT INTO ACCOUNT_TYPE VALUES ('PLOAN', 'Personal Loan Account', 0);
INSERT INTO ACCOUNT_TYPE VALUES ('HLOAN', 'Home Loan Account', 0);

-- CLIENT_TYPE
INSERT INTO CLIENT_TYPE VALUES ('I', 'Individual');
INSERT INTO CLIENT_TYPE VALUES ('N', 'Non-Individual');
INSERT INTO CLIENT_TYPE VALUES ('X', 'Inactive');

-- CLIENT_SUB_TYPE
INSERT INTO CLIENT_SUB_TYPE VALUES ('MAL', 'I', 'Male');
INSERT INTO CLIENT_SUB_TYPE VALUES ('FEM', 'I', 'Female');
INSERT INTO CLIENT_SUB_TYPE VALUES ('SME', 'N', 'Small to medium enterprise');
INSERT INTO CLIENT_SUB_TYPE VALUES ('COR', 'N', 'Corporate');
INSERT INTO CLIENT_SUB_TYPE VALUES ('X', 'X', 'Inactive');

-- CURRENCY
INSERT INTO CURRENCY VALUES ('USD', 2, 'United States dollar');
INSERT INTO CURRENCY VALUES ('ZAR', 2, 'South African rand');

-- CURRENCY_CONVERSION_RATE
INSERT INTO CURRENCY_CONVERSION_RATE VALUES ('USD', '*', '11.6167');

-- DENOMINATION_TYPE
INSERT INTO DENOMINATION_TYPE VALUES ('N', 'Note');
INSERT INTO DENOMINATION_TYPE VALUES ('C', 'Coin');

-- DENOMINATION
INSERT INTO DENOMINATION VALUES (1, 10, 'N');
INSERT INTO DENOMINATION VALUES (2, 20, 'N');
INSERT INTO DENOMINATION VALUES (3, 50, 'N');
INSERT INTO DENOMINATION VALUES (10, 5, 'C');

-- CLIENT
INSERT INTO CLIENT VALUES (1, 'Mr', 'Tao', 'Muzvidziwa', DATE '1980-01-01', 'MAL');

-- CLIENT_ACCOUNT
INSERT INTO CLIENT_ACCOUNT VALUES ('1001', 1, 'CHQ', 'ZAR', 1000.00);
INSERT INTO CLIENT_ACCOUNT VALUES ('1002', 1, 'CFCA', 'USD', 500.00);
INSERT INTO CLIENT_ACCOUNT VALUES ('1003', 1, 'CCRD', 'ZAR', 500.00);

-- CREDIT_CARD_LIMIT (if needed for repository)
INSERT INTO CREDIT_CARD_LIMIT VALUES ('1003', 2500);

-- ATM
INSERT INTO ATM VALUES (1, 'ATM1', 'Test Location');

-- ATM_ALLOCATION
INSERT INTO ATM_ALLOCATION VALUES (DEFAULT, 1, 1, 10);